version: '3'
services:
  db:
    image: mysql:latest
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - db:/var/lib/mysql
  app:
    build: .
    links:
      - db
    ports:
      - "8080:8080"
    environment:
      dockerdb: 'mysql+mysqlconnector://root@db:3306/ja'
volumes:
  db: